In [ ]:
#Importing Necessary Libraries
import pandas as pd

In [ ]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [ ]:
#Loading the data into variable
iris=load_iris()

In [ ]:
#using pandas dataframe, converting the data to dataframe
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [ ]:
#viewing the data
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
#making new column and assigning the target variable in dataframe
df['Species']=iris.target

In [ ]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Species  Is_train  
0          0      True  
1          0     False  
2          0      True  
3          0      True  
4          0      True  
..       ...       ...  
145        2      True  
146        2      True  
147        2      True  
148        2     False  
149        2      True  

[150 rows x 6 columns]

In [ ]:
# Using Describe line, we can get the detailed description of the dataframe
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)     Species  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [ ]:
#now spliting the data into a logic of 75% with True and remaining 25% with False value using Numpy random function
df['Is_train']=np.random.uniform(0,1,len(df)) <=.75

In [ ]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Species  Is_train  
0          0      True  
1          0      True  
2          0      True  
3          0      True  
4          0      True  
..       ...       ...  
145        2      True  
146        2      True  
147        2      True  
148        2     False  
149        2      True  

[150 rows x 6 columns]

In [ ]:
#spliting the training and testing data based on the "Is_train" column
train, test=df[df['Is_train']==True],df[df['Is_train']==False]

In [ ]:
#the shape command describe the shape of the data
train.shape

(103, 6)

In [ ]:
test.shape

(47, 6)

In [ ]:
#the len command describes the length of the data
len(train)

103

In [ ]:
len(test)

47

In [ ]:
# we are assigning new varialbe FEATURES with the columns from 0 to 4 except the target variable
FEATURES=df.columns[:4]

In [ ]:
FEATURES

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [ ]:
#here we are initializing the RandomForestClassifier model and defining the model
clf=RandomForestClassifier(n_jobs=2,random_state=0)

In [ ]:
#we are checking whether the command works correctly
train[FEATURES]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
149                5.9               3.0                5.1               1.8

[103 rows x 4 columns]

In [ ]:
#we are declaring the Y variable, that is the target variable


In [ ]:
y=train['Species']

In [ ]:
#not fitting the variables into the RandomForestClassifier model
clf.fit(train[FEATURES],y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [ ]:
#we are now predicting the model using the test features
clf.predict(test[FEATURES])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 2])

In [ ]:
#we determine the probability of the model for first 10 to 20 rows.
clf.predict_proba(test[FEATURES])[10:20]

array([[0.97, 0.03, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.99, 0.01],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.94, 0.06]])

In [ ]:
#we have predicted the outcome of the desired 
  clf.predict(test[FEATURES])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 2])

In [ ]:
#here we are verifying the target names
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
names = iris.target_names[clf.predict(test[FEATURES])]

In [ ]:
names


array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'versicolor',
       'virginica', 'virginica', 'virginica'], dtype='<U10')

In [ ]:
#using Crosstab feature from pandas to get to know how the data are processed and arranged.
pd.crosstab(test['Species'],names)

col_0    setosa  versicolor  virginica
Species                               
0            15           0          0
1             0          14          0
2             0           2         16